{
  "asyncapi":"2.0.0",
  "info":{
    "title":"Patient Service",
    "version":"0.3.0"
  },
  "servers":{
    "kafka":{
      "url":"kafka:9092",
      "protocol":"kafka"
    }
  },
  "channels":{
    "patients":{
      "subscribe":{
        "bindings":{
          "kafka":{

          }
        },
        "message":{
          "name":"com.albatha.nexthealth.patientsservice.dto.PatientCreatedEvent",
          "title":"PatientCreatedEvent",
          "payload":{
            "$ref":"#/components/schemas/PatientCreatedEvent"
          }
        }
      }
    }
  },
  "components":{
    "schemas":{
      "AddressDTO":{
        "type":"object",
        "properties":{
          "addressId":{
            "type":"string",
            "format":"uuid"
          },
          "flatVillaNumber":{
            "type":"string"
          },
          "buildingName":{
            "type":"string"
          },
          "formattedText":{
            "type":"string"
          },
          "userNotes":{
            "type":"string"
          },
          "area":{
            "type":"string"
          },
          "city":{
            "type":"string"
          },
          "state":{
            "type":"string"
          },
          "postalCode":{
            "type":"string"
          },
          "type":{
            "type":"string"
          },
          "country":{
            "type":"string"
          },
          "latitude":{
            "type":"number",
            "format":"double"
          },
          "longitude":{
            "type":"number",
            "format":"double"
          }
        },
        "example":{
          "addressId":"3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "flatVillaNumber":"string",
          "buildingName":"string",
          "formattedText":"string",
          "userNotes":"string",
          "area":"string",
          "city":"string",
          "state":"string",
          "postalCode":"string",
          "type":"string",
          "country":"string",
          "latitude":1.100000023841858,
          "longitude":1.100000023841858
        }
      },
      "InsuranceProviderDTO":{
        "type":"object",
        "properties":{
          "code":{
            "type":"string"
          },
          "name":{
            "type":"string"
          },
          "eClaimLinkId":{
            "type":"string"
          }
        },
        "example":{
          "code":"string",
          "name":"string",
          "eClaimLinkId":"string"
        }
      },
      "InsuranceDTO":{
        "type":"object",
        "properties":{
          "insId":{
            "type":"string"
          },
          "policyNumber":{
            "type":"string"
          },
          "network":{
            "type":"string"
          },
          "expiryDate":{
            "type":"string"
          },
          "insuranceProvider":{
            "$ref":"#/components/schemas/InsuranceProviderDTO"
          }
        },
        "example":{
          "insId":"string",
          "policyNumber":"string",
          "network":"string",
          "expiryDate":"string",
          "insuranceProvider":{
            "code":"string",
            "name":"string",
            "eClaimLinkId":"string"
          }
        }
      },
      "PatientCreatedEvent":{
        "type":"object",
        "properties":{
          "topic":{
            "type":"string"
          },
          "eventType":{
            "type":"string"
          },
          "data":{
            "$ref":"#/components/schemas/PatientDTO"
          }
        },
        "example":{
          "topic":"string",
          "eventType":"string",
          "data":{
            "patId":"string",
            "emiratesId":"string",
            "mohId":"string",
            "firstName":"string",
            "middleName":"string",
            "lastName":"string",
            "email":"string",
            "mobileNumber":"string",
            "dob":"string",
            "address":[
              {
                "addressId":"3fa85f64-5717-4562-b3fc-2c963f66afa6",
                "flatVillaNumber":"string",
                "buildingName":"string",
                "formattedText":"string",
                "userNotes":"string",
                "area":"string",
                "city":"string",
                "state":"string",
                "postalCode":"string",
                "type":"string",
                "country":"string",
                "latitude":1.100000023841858,
                "longitude":1.100000023841858
              }
            ],
            "insurances":[
              {
                "insId":"string",
                "policyNumber":"string",
                "network":"string",
                "expiryDate":"string",
                "insuranceProvider":{
                  "code":"string",
                  "name":"string",
                  "eClaimLinkId":"string"
                }
              }
            ]
          }
        }
      },
      "PatientDTO":{
        "type":"object",
        "properties":{
          "patId":{
            "type":"string"
          },
          "emiratesId":{
            "type":"string"
          },
          "mohId":{
            "type":"string"
          },
          "firstName":{
            "type":"string"
          },
          "middleName":{
            "type":"string"
          },
          "lastName":{
            "type":"string"
          },
          "email":{
            "type":"string"
          },
          "mobileNumber":{
            "type":"string"
          },
          "dob":{
            "type":"string"
          },
          "address":{
            "uniqueItems":true,
            "type":"array",
            "items":{
              "$ref":"#/components/schemas/AddressDTO"
            }
          },
          "insurances":{
            "uniqueItems":true,
            "type":"array",
            "items":{
              "$ref":"#/components/schemas/InsuranceDTO"
            }
          }
        },
        "example":{
          "patId":"string",
          "emiratesId":"string",
          "mohId":"string",
          "firstName":"string",
          "middleName":"string",
          "lastName":"string",
          "email":"string",
          "mobileNumber":"string",
          "dob":"string",
          "address":[
            {
              "addressId":"3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "flatVillaNumber":"string",
              "buildingName":"string",
              "formattedText":"string",
              "userNotes":"string",
              "area":"string",
              "city":"string",
              "state":"string",
              "postalCode":"string",
              "type":"string",
              "country":"string",
              "latitude":1.100000023841858,
              "longitude":1.100000023841858
            }
          ],
          "insurances":[
            {
              "insId":"string",
              "policyNumber":"string",
              "network":"string",
              "expiryDate":"string",
              "insuranceProvider":{
                "code":"string",
                "name":"string",
                "eClaimLinkId":"string"
              }
            }
          ]
        }
      }
    }
  }
}