{
  "asyncapi":"2.0.0",
  "info":{
    "title":"Payment Service API",
    "version":"0.3.0"
  },
  "servers":{
    "kafka":{
      "url":"kafka:9092",
      "protocol":"kafka"
    }
  },
  "channels":{
    "payment":{
      "subscribe":{
        "bindings":{
          "kafka":{

          }
        },
        "message":{
          "name":"com.albatha.paymentservice.dto.PaymentMethodCreatedEvent",
          "title":"PaymentMethodCreatedEvent",
          "payload":{
            "$ref":"#/components/schemas/PaymentMethodCreatedEvent"
          }
        }
      },
      "bindings":{
        "kafka":{

        }
      }
    }
  },
  "components":{
    "schemas":{
      "WalletDetailsOutputDTO":{
        "type":"object",
        "exampleSetFlag":true
      },
      "PaymentMethodOutputDTO":{
        "required":[
          "billingDetails",
          "type"
        ],
        "type":"object",
        "properties":{
          "type":{
            "type":"string",
            "exampleSetFlag":false,
            "enum":[
              "CARD",
              "WALLET"
            ]
          },
          "billingDetails":{
            "$ref":"#/components/schemas/BillingDetailsDTO",
            "exampleSetFlag":false
          },
          "card":{
            "$ref":"#/components/schemas/CardDetailsOutputDTO",
            "exampleSetFlag":false
          },
          "wallet":{
            "$ref":"#/components/schemas/WalletDetailsOutputDTO",
            "exampleSetFlag":false
          },
          "default":{
            "type":"boolean",
            "exampleSetFlag":false
          }
        },
        "example":{
          "type":"CARD",
          "billingDetails":{
            "address":{
              "city":"string",
              "country":"string",
              "line1":"string",
              "line2":"string",
              "postalCode":"string",
              "state":"string"
            },
            "email":"string",
            "name":{
              "firstName":"string",
              "middleName":"string",
              "lastName":"string",
              "fullName":"string"
            },
            "phone":"string"
          },
          "card":{
            "expiryYear":"string",
            "expiryMonth":"string",
            "nameOnCard":"string",
            "cvcCheckStatus":"string",
            "funding":"string",
            "maskedCardNumber":"string"
          },
          "default":true
        },
        "exampleSetFlag":true
      },
      "PersonNameDTO":{
        "type":"object",
        "properties":{
          "firstName":{
            "type":"string",
            "exampleSetFlag":false
          },
          "middleName":{
            "type":"string",
            "exampleSetFlag":false
          },
          "lastName":{
            "type":"string",
            "exampleSetFlag":false
          },
          "fullName":{
            "type":"string",
            "exampleSetFlag":false
          }
        },
        "example":{
          "firstName":"string",
          "middleName":"string",
          "lastName":"string",
          "fullName":"string"
        },
        "exampleSetFlag":true
      },
      "BillingDetailsDTO":{
        "type":"object",
        "properties":{
          "address":{
            "$ref":"#/components/schemas/AddressDTO",
            "exampleSetFlag":false
          },
          "email":{
            "type":"string",
            "exampleSetFlag":false
          },
          "name":{
            "$ref":"#/components/schemas/PersonNameDTO",
            "exampleSetFlag":false
          },
          "phone":{
            "type":"string",
            "exampleSetFlag":false
          }
        },
        "example":{
          "address":{
            "city":"string",
            "country":"string",
            "line1":"string",
            "line2":"string",
            "postalCode":"string",
            "state":"string"
          },
          "email":"string",
          "name":{
            "firstName":"string",
            "middleName":"string",
            "lastName":"string",
            "fullName":"string"
          },
          "phone":"string"
        },
        "exampleSetFlag":true
      },
      "CardDetailsOutputDTO":{
        "type":"object",
        "properties":{
          "expiryYear":{
            "type":"string",
            "exampleSetFlag":false
          },
          "expiryMonth":{
            "type":"string",
            "exampleSetFlag":false
          },
          "nameOnCard":{
            "type":"string",
            "exampleSetFlag":false
          },
          "cvcCheckStatus":{
            "type":"string",
            "exampleSetFlag":false
          },
          "funding":{
            "type":"string",
            "exampleSetFlag":false
          },
          "maskedCardNumber":{
            "type":"string",
            "exampleSetFlag":false
          }
        },
        "example":{
          "expiryYear":"string",
          "expiryMonth":"string",
          "nameOnCard":"string",
          "cvcCheckStatus":"string",
          "funding":"string",
          "maskedCardNumber":"string"
        },
        "exampleSetFlag":true
      },
      "AddressDTO":{
        "type":"object",
        "properties":{
          "city":{
            "type":"string",
            "exampleSetFlag":false
          },
          "country":{
            "type":"string",
            "exampleSetFlag":false
          },
          "line1":{
            "type":"string",
            "exampleSetFlag":false
          },
          "line2":{
            "type":"string",
            "exampleSetFlag":false
          },
          "postalCode":{
            "type":"string",
            "exampleSetFlag":false
          },
          "state":{
            "type":"string",
            "exampleSetFlag":false
          }
        },
        "example":{
          "city":"string",
          "country":"string",
          "line1":"string",
          "line2":"string",
          "postalCode":"string",
          "state":"string"
        },
        "exampleSetFlag":true
      },
      "PaymentMethodCreatedEvent":{
        "type":"object",
        "properties":{
          "topic":{
            "type":"string",
            "exampleSetFlag":false
          },
          "eventType":{
            "type":"string",
            "exampleSetFlag":false
          },
          "data":{
            "$ref":"#/components/schemas/PaymentMethodOutputDTO",
            "exampleSetFlag":false
          }
        },
        "example":{
          "topic":"string",
          "eventType":"string",
          "data":{
            "type":"CARD",
            "billingDetails":{
              "address":{
                "city":"string",
                "country":"string",
                "line1":"string",
                "line2":"string",
                "postalCode":"string",
                "state":"string"
              },
              "email":"string",
              "name":{
                "firstName":"string",
                "middleName":"string",
                "lastName":"string",
                "fullName":"string"
              },
              "phone":"string"
            },
            "card":{
              "expiryYear":"string",
              "expiryMonth":"string",
              "nameOnCard":"string",
              "cvcCheckStatus":"string",
              "funding":"string",
              "maskedCardNumber":"string"
            },
            "default":true
          }
        },
        "exampleSetFlag":true
      }
    }
  }
}